### ISSUE TITLE
Make Fans more expensive

### ISSUE THREAD

**Issue by BrekiTomasson** [FettLol/FettLolUtilMod#11]
Fans, introduced by the `MobFarmHelpers` mod, are surprisingly easy to make - both the fan itself and the fan 'block'.

`mobfarmutilities:fan_blade` requires four `minecraft:iron_ingot` and one `minecraft:iron_bars`. While this is mostly fine, I believe replacing the Ingots with `techreborn:iron_plate`, as this is more in line with the kind of shape the actual fan blade has.

`mobfarmutilities:fan` currently requires one `mobfarmutilities:fan_blade`, four more `minecraft:iron_ingot`, and four `minecraft:redstone`. Replacing this with a shapeless recipe requiring just one `techreborn:advanced_machine_frame` and one `mobfarmutilities:fan_blade` might make more sense.

**Comment by Fourmisain** [comment]
> `mobfarmutilities:fan_blade` requires four `minecraft:iron_ingot` and one `minecraft:iron_bars`. While this is mostly fine, I believe replacing the Ingots with `techreborn:iron_plate`, as this is more in line with the kind of shape the actual fan blade has.

That won't make it more expensive though.

> `mobfarmutilities:fan` currently requires one `mobfarmutilities:fan_blade`, four more `minecraft:iron_ingot`, and four `minecraft:redstone`. Replacing this with a shapeless recipe requiring just one `techreborn:advanced_machine_frame` and one `mobfarmutilities:fan_blade` might make more sense.

That's pretty good, still very cheap.
Maybe we should suggest to the dev to make upgrading fans more expensive or configurable? Because that seems like the best way to balance it.

**Comment by BrekiTomasson** [comment]
> That won't make it more expensive though.

No, but it will increase the requirements of getting it as the player will have to first build the infrastructure required to get the Iron Plates.

> That's pretty good, still very cheap.

It is, it is, but I still feel it's kind of balanced. The fans aren't super useful except in some very specific situations and I think this would most likely be a suitable balance for it.

As for asking the dev to make upgrades configurable; that's definitely something we should look into separately.

**Comment by Fourmisain** [comment]
> The fans aren't super useful except in some very specific situations

 I _vehemently_ disagree!

Those fans make building a mob farm a breeze (pun intended) and they highly increase their efficiency too because time to kill is vastly reduced.

Like take the overworld farm I built: there's no need to use water (which blocks mob spawns) to slooowly push the mobs off the edge and again slooowly into the hole. Just blast them sideways off the spawn platforms, use a line of water to catch them and blast them right above the hole to fall in, bam, efficiency just increased tenfold and you can remove all the redstone too.

The endermen farm is similar, no need to use an endermite to lure the endermen into the hole (where they often stop right at the edge), just blast them.

**Comment by BrekiTomasson** [comment]
![image](https://user-images.githubusercontent.com/7026735/113689885-159bed80-96cb-11eb-8794-79fe88e3280f.png)

How about something like this? Advanced Machine Casing at the bottom, six Steel Plates along the side, Redstone dust and a Fan Blade along the middle.

**Comment by Fourmisain** [comment]
Looks pretty good!
Was thinking about an Industrial Machine Casing, but since you usually need more than 1 fan and those things cost 6 Chrome (for reference: I got 43), I think this should be fine!
