### ISSUE TITLE
Make Item Collectors more Expensive (or remove entirely)

### ISSUE THREAD

**Issue by BrekiTomasson** [FettLol/FettLolUtilMod#12]
The Item Collector, added by MobFarmUtilities is a very convenient tool that makes it extremely simple to gather materials from automated mob farms. Because of this, it needs to be far more expensive than just five `minecraft:iron_ingot`, one `minecraft:ender_pearl`, two `minecraft:redstone` and one `minecraft:iron_bars`. This should be considered a near-endgame resource and thus require more expensive and/or hard-to-get materials.

First idea I have is something like this, wrapping a `minecraft:hopper` and a `#c:wooden_chest` with seven `techreborn:advanced_machine_frame`: 

![image](https://user-images.githubusercontent.com/7026735/113517884-fdb95200-9582-11eb-8fd4-29d041ab747b.png)

Another alterrnative, of course, is to remove the item altogether, but that would be a last-resort kind of thing. I believe that with a balanced recipe, this item could work well and remove the dependence on long hopper chains and/or the problems associated with hopper minecart collection systems.

**Comment by Fourmisain** [comment]
Instead of 7 Machine Frames (which is just some iron, coal and mixed metals), I'd use 1 Industrial Machine Frame as a base because it requires Chrome and Titanium which are both really rare and the industrial frames can only be found in end cities.
Not sure what to add around it though.

**Comment by BrekiTomasson** [comment]
How about Hopper + Chest + Industrial Machine Frame? We don't have to fill the entire 3x3 grid.

**Comment by Fourmisain** [comment]
When the xp collector uses soul shards/gems, the item collector should probably use something along those lines too.
And repeating my thoughts, since the item collector is much more useful, it should also be more expensive.
