### ISSUE TITLE
Make Experience Collectors more expensive (or remove entirely)

### ISSUE THREAD

**Issue by BrekiTomasson** [FettLol/FettLolUtilMod#13]
The Experience Collector, added by `Mob Farm Helpers` is another convenient block to add in various kinds of farms, but the recipe to build it is farly cheap. It requires one `mobfarmhelpers:item_collector` and eight `minecraft:lapis_lazuli`. While some of this will be fixed by making the Item Collector more difficult to get (see #12 for details), this item needs to be made more expensive as well. 

Since experience is mostly gotten by killing mobs, I think it makes sense to make use of the `fettlol:soul_shard` or `fettlol:soul_gem` here, as these are associated to the souls of mobs. Maybe something like this?

![image](https://user-images.githubusercontent.com/7026735/113518157-bcc23d00-9584-11eb-8dff-07e01dfde8fe.png)

**Comment by BrekiTomasson** [comment]
Interesting discovery: Using an empty `minecraft:bucket` on an Experience Collector with 1000 or more stored experience will give you a `mobfarmutilities:liquid_experience_bucket`, which can be emptied out onto the ground, giving you a green fluid of some sort. This fluid can then be captured inside a `techreborn:cell`, giving you a Tech Reborn Liquid Experience Cell.

**Comment by Fourmisain** [comment]
2 Soul Gems is waaaaay overpriced, need I remind you I only got 1 in what feels like 2 months of play time?
2 Soul _Shards_ should be more than enough.

I don't even think the xp collector is anything special. It stores some xp but since there's no automatic way to produce xp without a player, there's little reason to actually do use it - if you need xp, you sit at your farm, if you don't, you don't.

While I like the idea of basing the recipe it off the item collector, I feel the item collector is way more valuable than the xp collector, so maybe it should have an independent, cheaper recipe.

**Comment by BrekiTomasson** [comment]
Soul Shards are bugged on the server at the moment. Play with the current `v1.12` branch and see if your experience with Soul Shards/Soul Gems is the same.

As for the independent recipe, I agree. How about replacing the Item Collector with an Industrial Machine Frame?

**Comment by Fourmisain** [comment]
> Soul Shards are bugged on the server at the moment.

I know, still, I've mined far less than 150 diamond ore, no more than 80 I think, so I wouldn't have 2 Soul Gems.
Most my diamonds are from smelting diamond gear and finding them in treasure chests, at some point there's very little incentive to go mining for diamonds.

It's just not right that extremely useful Spawners cost 1 Soul Gem while questionably useful xp collectors cost 2.

> How about replacing the Item Collector with an Industrial Machine Frame?

That works I guess, though comparing with the suggestion for the Item Collector, the xp collector would be more expensive (even when going with "just" 2 soul shards).

**Comment by BrekiTomasson** [comment]
You're right. I think soul shards is the way to go for the Experience Collector, and then we'll find a way to make the Item Collector more expensive instead.

**Comment by BrekiTomasson** [comment]
Implemented in 9960a8e56fed36e9cbee8c9df54c3fd801b749eb alongside other refactoring having to do with custom recipes.
