### ISSUE TITLE
Mod Integrations can potentially fail due to load order

### ISSUE THREAD

**Issue by Fourmisain** [FettLol/FettLolUtilMod#2]
Pretty sure that's (still) the case.
Starting fettlol and watching the logs shows some mods are loaded after fettlol

> [main/INFO] [fettlol]: Starting FettLol Utility Mod.
[main/INFO] [fettlol]: Draylar's Battle Towers detected! Applying integrations.
[main/INFO] [fettlol]: Better End detected! Applying integrations.
[main/INFO] [fettlol]: Biomes You'll Go detected! Applying integrations.
[main/INFO] [fettlol]: Croptopia detected! Applying integrations!
[main/INFO] [fettlol]: Dank Storage detected! Applying integrations.
[main/INFO] [fettlol]: Midas Hunger detected! Applying integrations!
[main/INFO] [fettlol]: Ring of Attraction detected! Applying integrations!
[main/INFO] [fettlol]: Winged detected! Applying integrations!
[main/INFO] [cotton-datapack]: [Cotton Datapack]: Loaded config.
[main/INFO] [REI]: Config loaded.
[main/INFO] [class_2983]: [STDOUT]: The Parakeet Mod has been successfully initialized.
[main/INFO] [CharmClient]: Setting up client modules for 'charm'
...

It doesn't seem critical at the moment, but it might become critical in the future.

I tried moving the integrations behind a `ResourceType.SERVER_DATA` ReloadListener, but it looked like this is too late since I got a bunch of errors like
> [Server thread/ERROR] [class_3441]: Tried to load unrecognized recipe: fettlol:betterend/terminite_sword removed now.
[Server thread/ERROR] [class_3441]: Tried to load unrecognized recipe: fettlol:byg/ametrine_leggings removed now.
...

This comes back to finding a later "init" event.

**Comment by BrekiTomasson** [comment]
Yeah, this is on my list of "things to look at later, since they could be a problem at some point".

... Now, what label would that be? :D

**Comment by Fourmisain** [comment]
Mod integrations are currently only changing recipes and loot tables.
Recipes are added to a list which is then used in a mixin.
Loot tables are registered in an event.

In other words, there's no race condition here, no need for a "late init".
