### ISSUE TITLE
Make resource pack optional/modular

### ISSUE THREAD

**Issue by Fourmisain** [FettLol/FettLolUtilMod#20]
The internal resource pack changes _a lot_ of things that are very subjective like the 3D block models that are also performance critical due to [LambDynamicLight, issue](https://github.com/LambdAurora/LambDynamicLights/issues) 16 (don't want to direct link it, because that'd turn into a mention/notification), most notably magma and quartz blocks, but it's really any 3D block that lags the game.

Another example I found while trying turning off Better Enchanted Books;

Fettlol:
![fettlol](https://user-images.githubusercontent.com/8464472/115111026-8d490280-9f7e-11eb-92a2-3b56c17b65a6.gif)
Vanilla:
![vanilla](https://user-images.githubusercontent.com/8464472/115111025-8cb06c00-9f7e-11eb-8d17-3e1d4e6340f9.gif)
At first, I thought this was a bug of some kind due to the ribbon being purple and most of the glint missing.

It is possible to undo changes by adding a custom resource pack which overwrites them again, but it's tedious to scoure through the pack, since it's very hard to distinguish "fettlol changes" vs VanillaTweaks changes.

Ideally, the fettlol-modpack should have multiple resource packs, like a "base fettlol", a VanillaTweaks one, another one for the 3D models, possibly more for some more noticable changes like the steel like iron, the sun/moon and maybe the rain sounds.

**Comment by BrekiTomasson** [comment]
Yeah, I've been having thoughts along these lines as well, but haven't decided exactly how best to separate things. I'll add this to the backlog for v1.13. I've got some general ideas already.

**Comment by BrekiTomasson** [comment]
Custom enchantment glint has been removed in the dev branch, and multiple textures have been moved out of the modpack into one of two resource packs, "3D Ores" and "3D Blocks". Additional tweaks are in progress, with the ambition being that this mod should only change the textures of those blocks that are judged to be part of the group that gives the modpack its overall "feel" (grass, wool, concrete,  terracotta, etc). More "opinionated" changes, tweaks and adjustments should ideally be moved into separate texture packs or use existing texture packs.
